/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.views;

import com.mycompany.controller.ChatController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Admin
 */
public class ClientGUIJframe extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUIJframe
     */
    public ClientGUIJframe() {
        initComponents();
        ChatController controller = new ChatController(jtfUser, jtfHost, jtfPort, btnSend, btnConnect, jtaHistoryChat, jtaMessage, jpnUser, btnLogOut);
        controller.setHandle();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (jtfUser.getText().isEmpty() && !btnLogOut.isEnabled()) {
                    System.exit(0);
                } else {
                    controller.endProcess();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jlbUser = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jtfHost = new javax.swing.JTextField();
        jtfPort = new javax.swing.JTextField();
        jlbPort = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        jpnChat6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaHistoryChat = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jpnUser = new javax.swing.JPanel();
        jlbHost = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(222, 222, 222));

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));
        jpnRoot.setForeground(new java.awt.Color(0, 0, 0));

        jlbUser.setForeground(new java.awt.Color(0, 0, 0));
        jlbUser.setText("User");

        jtfUser.setBackground(new java.awt.Color(240, 240, 240));
        jtfUser.setForeground(new java.awt.Color(0, 0, 0));

        jtfHost.setEditable(false);
        jtfHost.setBackground(new java.awt.Color(240, 240, 240));
        jtfHost.setForeground(new java.awt.Color(0, 0, 0));
        jtfHost.setText("127.0.0.1");
        jtfHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHostActionPerformed(evt);
            }
        });

        jtfPort.setEditable(false);
        jtfPort.setBackground(new java.awt.Color(240, 240, 240));
        jtfPort.setForeground(new java.awt.Color(0, 0, 0));
        jtfPort.setText("8888");
        jtfPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPortActionPerformed(evt);
            }
        });

        jlbPort.setForeground(new java.awt.Color(0, 0, 0));
        jlbPort.setText("Port");

        btnConnect.setBackground(new java.awt.Color(255, 255, 255));
        btnConnect.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnConnect.setForeground(new java.awt.Color(255, 0, 50));
        btnConnect.setText("CONNECT");

        jpnChat6.setBackground(new java.awt.Color(222, 222, 222));
        jpnChat6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("History");

        jtaHistoryChat.setEditable(false);
        jtaHistoryChat.setBackground(new java.awt.Color(255, 255, 255));
        jtaHistoryChat.setColumns(20);
        jtaHistoryChat.setForeground(new java.awt.Color(0, 0, 0));
        jtaHistoryChat.setLineWrap(true);
        jtaHistoryChat.setRows(5);
        jtaHistoryChat.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtaHistoryChat);

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Type message here to send");

        jtaMessage.setBackground(new java.awt.Color(255, 255, 255));
        jtaMessage.setColumns(20);
        jtaMessage.setForeground(new java.awt.Color(0, 0, 0));
        jtaMessage.setLineWrap(true);
        jtaMessage.setRows(5);
        jtaMessage.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jtaMessage);

        btnSend.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jpnUser.setBackground(new java.awt.Color(222, 222, 222));
        jpnUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnUser.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpnUserLayout = new javax.swing.GroupLayout(jpnUser);
        jpnUser.setLayout(jpnUserLayout);
        jpnUserLayout.setHorizontalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnUserLayout.setVerticalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnChat6Layout = new javax.swing.GroupLayout(jpnChat6);
        jpnChat6.setLayout(jpnChat6Layout);
        jpnChat6Layout.setHorizontalGroup(
            jpnChat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChat6Layout.createSequentialGroup()
                .addGroup(jpnChat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnChat6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnChat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnChat6Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel1))
                    .addGroup(jpnChat6Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnChat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnChat6Layout.setVerticalGroup(
            jpnChat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChat6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jpnChat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnChat6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(jpnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jpnChat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jlbHost.setForeground(new java.awt.Color(0, 0, 0));
        jlbHost.setText("Host");

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 0, 50));
        btnLogOut.setText("LOG OUT");

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnChat6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jlbHost, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfHost, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jlbPort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConnect)))
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbPort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnConnect)
                                .addComponent(btnLogOut))
                            .addComponent(jlbHost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnRootLayout.createSequentialGroup()
                        .addComponent(jtfHost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jpnChat6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void jtfHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHostActionPerformed

    private void jtfPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPortActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbHost;
    private javax.swing.JLabel jlbPort;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JPanel jpnChat6;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnUser;
    private javax.swing.JTextArea jtaHistoryChat;
    private javax.swing.JTextArea jtaMessage;
    private javax.swing.JTextField jtfHost;
    private javax.swing.JTextField jtfPort;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables
}
